### PR TITLE
Added tests for other raw value types

### PR DESCRIPTION
**Pull request by arthur-here**
Also merged commits from upstream branch to fix Travis build

### CODE REVIEW

**Comment by litso** [comment]
Hi @burntheroad Thanks for the added tests! Would prefer not have all these commits in the PR. Can you make a PR with just the test changes (and without the merge commit)?  If you like I can rebase to upstream first.

**Comment by arthur-here** [comment]
Oh, sorry. I've reverted the merge with upstream in the current PR. Is it ok or I've done something wrong?

**Comment by litso** [comment]
Do you mind if i rebase to upstream and submitting another PR?

**Comment by litso** [comment]
Ok litso:enum-suppport is updated. Would you mind opening another PR? Thanks and sorry for the hassle

**Comment by arthur-here** [comment]
Should I also update my branch or can open PR as is?

**Comment by litso** [comment]
Ideally rebase onto litso:enum-support.  There were merge conflicts in the project file so you might have to revert your commit, stash the changes and just unstash them on top of HEAD

Thanks again

**Pull request closed without merging**
